
export const localDBAutocomplete = [
    { title: 'Beautiful'},
    { title: 'Photography'},
    { title: 'Beach'},
    { title: 'Chocolate'},
    { title: 'Recipes'},
    { title: 'Best'},
    { title: 'Travel'},
    { title: 'Beginner'},
  ];
  
export const localDBResults = [
    { title: 'Beautiful Beach Resorts', description: 'Explore stunning beach resorts around the world.', link: 'https://example.com/beach-resorts'},
    { title: 'Delicious Chocolate Recipes', description: 'Indulge in mouth-watering chocolate treats with these recipes.', link: 'https://example.com/chocolate-recipes'},
    { title: 'Photography Tips for Beginners', description: 'Learn the basics of photography and capture amazing moments.', link: 'https://example.com/photography-tips'},
    { title: 'Healthy Salad Recipes', description: 'Discover nutritious and tasty salad recipes for a balanced diet.', link: 'https://example.com/salad-recipes'},
    { title: 'DIY Home Decor Ideas', description: 'Get creative with these do-it-yourself home decor projects.', link: 'https://example.com/diy-home-decor'},
    { title: 'Best Sci-Fi Movies of All Time', description: 'Explore the most iconic science fiction movies that have left a lasting impact.', link: 'https://example.com/best-sci-fi-movies'},
    { title: 'Top Travel Destinations in 2023', description: 'Plan your next adventure with the hottest travel destinations for the upcoming year.', link: 'https://example.com/top-travel-destinations'},
    { title: 'Introduction to Machine Learning', description: 'Dive into the world of machine learning and understand its fundamental concepts.', link: 'https://example.com/machine-learning-intro'},
    { title: 'Quick and Easy Dinner Recipes', description: 'Cook delicious dinners in no time with these quick and easy recipes.', link: 'https://example.com/easy-dinner-recipes'},
    { title: 'Beginner\'s Guide to Gardening', description: 'Start your own garden with this comprehensive beginner\'s guide to gardening.', link: 'https://example.com/gardening-guide'},
    { title: 'Exotic Hiking Trails', description: 'Embark on a journey through breathtaking hiking trails around the globe.', link: 'https://example.com/exotic-hiking-trails'},
    { title: 'Decadent Dessert Delights', description: 'Satisfy your sweet tooth with these indulgent and mouthwatering dessert recipes.', link: 'https://example.com/dessert-delights'},
    { title: 'Mastering Night Photography', description: 'Capture stunning images in low light with expert tips on night photography.', link: 'https://example.com/night-photography-tips'},
    { title: 'Vegan Delicacies', description: 'Explore a world of delicious vegan recipes that are both healthy and flavorful.', link: 'https://example.com/vegan-delicacies'},
    { title: 'Crafting DIY Pet Accessories', description: 'Show your furry friends some love with handmade accessories for pets.', link: 'https://example.com/diy-pet-accessories'},
    { title: 'Classic Horror Movies Marathon', description: 'Experience spine-chilling moments with a marathon of the best classic horror movies.', link: 'https://example.com/classic-horror-movies'},
    { title: 'Hidden Gems in European Cities', description: 'Uncover lesser-known treasures in European cities for a unique travel experience.', link: 'https://example.com/hidden-gems-europe'},
    { title: 'Advanced Data Science Techniques', description: 'Deepen your understanding of data science with advanced techniques and methodologies.', link: 'https://example.com/advanced-data-science'},
    { title: '30-Minute Healthy Lunch Ideas', description: 'Prepare delicious and nutritious lunches in just 30 minutes with these recipes.', link: 'https://example.com/healthy-lunch-ideas'},
    { title: 'Indoor Plants for a Green Home', description: 'Bring nature indoors with a selection of easy-to-care-for indoor plants.', link: 'https://example.com/indoor-plants-green-home'},
    { title: 'Adventurous Mountain Climbs', description: 'Conquer the heights with these thrilling and challenging mountain climbs.', link: 'https://example.com/mountain-climbs'},
    { title: 'Gourmet Coffee Brewing at Home', description: 'Transform your coffee experience with gourmet brewing techniques you can do at home.', link: 'https://example.com/gourmet-coffee-brewing'},
    { title: 'Urban Street Photography Guide', description: 'Capture the essence of city life with this guide to urban street photography.', link: 'https://example.com/urban-street-photography'},
    { title: 'Plant-Based Protein Recipes', description: 'Explore tasty and protein-packed recipes with a focus on plant-based ingredients.', link: 'https://example.com/plant-based-protein-recipes'},
    { title: 'DIY Kids', description: 'Keep the little ones entertained with creative and fun DIY crafts for rainy days.', link: 'https://example.com/diy-kids-crafts'},
    { title: 'Classic Literature Must-Reads', description: 'Immerse yourself in timeless literature with these must-read classic novels.', link: 'https://example.com/classic-literature'},
    { title: 'Unusual Adventure Sports', description: 'Experience an adrenaline rush with these unusual and thrilling adventure sports.', link: 'https://example.com/adventure-sports'},
    { title: 'Blockchain and Cryptocurrency Basics', description: 'Gain insights into the fundamentals of blockchain technology and cryptocurrencies.', link: 'https://example.com/blockchain-crypto-basics'},
    { title: 'Simple One-Pan Dinner Recipes', description: 'Simplify your dinner routine with delicious and easy one-pan recipes for busy nights.', link: 'https://example.com/one-pan-dinner-recipes'},
    { title: 'Container Gardening for Small Spaces', description: 'Create a vibrant garden in limited space with container gardening tips and ideas.', link: 'https://example.com/container-gardening'},
    { title: 'Epic Road Trip Routes', description: 'Hit the open road and explore these epic and picturesque road trip routes.', link: 'https://example.com/epic-road-trip-routes'},
    { title: 'Savory and Spicy BBQ Recipes', description: 'Fire up the grill with these savory and spicy barbecue recipes for outdoor feasts.', link: 'https://example.com/bbq-recipes'},
    { title: 'Astrophotography for Beginners', description: 'Capture the beauty of the night sky with beginner-friendly astrophotography tips.', link: 'https://example.com/astrophotography-beginners'},
    { title: 'Mediterranean Diet Delights', description: 'Embrace a healthy lifestyle with delicious recipes inspired by the Mediterranean diet.', link: 'https://example.com/mediterranean-diet-delights'},
    { title: 'DIY Eco-Friendly Home Projects', description: 'Transform your home with eco-friendly DIY projects for a sustainable living space.', link: 'https://example.com/eco-friendly-home-projects'},
    { title: 'Classic Jazz Albums to Explore', description: 'Dive into the world of jazz with a curated list of classic albums that define the genre.', link: 'https://example.com/classic-jazz-albums'},
    { title: 'Unconventional Camping Spots', description: 'Experience the thrill of camping in unconventional and unique locations.', link: 'https://example.com/unconventional-camping-spots'},
    { title: 'Introduction to Quantum Computing', description: 'Explore the fascinating world of quantum computing and its potential impact.', link: 'https://example.com/quantum-computing-intro'},
    { title: '30-Minute Dessert Recipes', description: 'Indulge your sweet tooth with quick and delightful dessert recipes that take only 30 minutes.', link: 'https://example.com/30-minute-dessert-recipes'},
    { title: 'Balcony Gardening Tips for Urban Dwellers', description: 'Create a lush garden oasis on your balcony with these practical gardening tips.', link: 'https://example.com/balcony-gardening-tips'},
  ];